### ISSUE TITLE
Open-Source Tools

### ISSUE THREAD

**Issue by KChavez04** [ORNL-AMO/Utility-Optical-Recognition#3]
As a Project Lead, I want to use open-source tools, so that our product can remain free to end users.

**Comment by CharvelHJohnson** [comment]
**Tesseract OCR**
- https://www.ttmind.com/techpost/how-to-extract-text-from-image-using-angularocr-with-tessera

**React Easy Crop**
- https://github.com/ValentinH/react-easy-crop/blob/main/examples/src/index.tsx
