### ISSUE TITLE
To-Do-List

### ISSUE THREAD

**Issue by rileytsmith** [ORNL-AMO/Utility-Optical-Recognition#6]
As a Relationship Manager, I want a column (the “to do” list) beside the utility bill image that describes all the utility data that needs to be selected, so that the end user can understand what information is needed.

**Comment by KChavez04** [comment]
**Required Fields Per Utility Type in VERIFI'S UI**

Electricity
-Meter Read Date mm/dd/yyyy
-Total Energy Use kWh?

Natural Gas
-Meter Read Date mm/dd/yyyy
-Total Energy Use Therm

Solar
-Meter Read Date mm/dd/yyyy
-Total Energy Use kWh

Other Fuels
-Meter Read Date mm/dd/yyyy
-Total Volume SCF
-Total Energy Use MMBtu

Other Energy
-Meter Read Date mm/dd/yyyy
-Total Volume lb
-Total Energy Use MMBtu

Water
-Meter Read Date mm/dd/yyyy
-Total Volume gal

Waste Water
-Meter Read Date mm/dd/yyyy
-Total Volume gal

Other Utility
-Meter Read Date mm/dd/yyyy

**Comment by KChavez04** [comment]
**Required Fields For All Utilities per interface IdbUtilityMeterData in idb**
_x indicates that it is pulled in via editMeterData_
`checked` X
`totalCost`
`totalEnergyUse`
`readDate` ?
`accountId` X
`facilityId` X
`meterId` X
`guid` X

**Comment by KChavez04** [comment]
electricity/solar
meter read date
total energy use
total real demand
total billed demand
total cost

meter read date
total volume
total energy use
total cost
commodity charge
delivery charges
other charges

other utility
meter read date
total cost
commodity charge
delivery charges
other charges
