### ISSUE TITLE
Prompt for what to select on image

### ISSUE THREAD

**Issue by rileytsmith** [ORNL-AMO/Utility-Optical-Recognition#9]
As a Relationship Manager, I want a prompt at the top of the page for each piece of utility bill information that needs to be selected on the page, so that the end user can easily follow what needs to be selected.

**Comment by EthanOwens** [comment]
Prompt user to have all required fields done if any required fields are empty.

**Comment by KChavez04** [comment]
Ideas
- Asterisk for each of the required items
- Additional alert (red bg) when you click save and required item has not been worked
